#+ summary:
#+   Show me a list of all recorded taxa by Heinrich Kuhl (http://viaf.org/viaf/4506482) and the pages where these can be found.
#+ tags:
#+   - Q-02
#+ endpoint: http://makingsense.liacs.nl/rdf4j-server/repositories/NC
#+ endpoint_in_url: False

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX nhc: <http://makingsense.liacs.nl/rdf/nhc/>
PREFIX nc: <http://testingsense.liacs.nl/rdf/nc#>
PREFIX dwc: <http://rs.tdwg.org/dwc/>
PREFIX dwciri: <http://rs.tdwg.org/dwc/iri/>
PREFIX dsw: <http://purl.org/dsw/>
PREFIX viaf: <http://viaf.org/viaf/>
PREFIX oa: <http://www.w3.org/ns/oa#>
SELECT DISTINCT ?label ?page WHERE {
  ?taxon rdfs:label ?label .
  ?identification dwciri:toTaxon ?taxon .
  ?identification dsw:isBasedOn ?humanobservation .
  ?annotation oa:hasBody ?humanobservation .
  ?annotation oa:hasTarget ?page .
  ?organism dsw:hasIdentification ?identification .
  ?occurrence dsw:occurrenceOf ?organism .
  ?occurrence dwciri:recordedBy viaf:45106482
}
