#+ summary:
#+   Provide me with a list of all later added identifications
#+ tags:
#+   - Q-07
#+ endpoint: http://makingsense.liacs.nl/rdf4j-server/repositories/NC
#+ endpoint_in_url: False

PREFIX nhc: <http://makingsense.liacs.nl/rdf/nhc/>
PREFIX dwciri: <http://rs.tdwg.org/dwc/iri/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?label WHERE {
  ?organism nhc:additionalIdentification ?additional .
  ?additional dwciri:toTaxon ?taxon .
  ?taxon rdfs:label ?label
}
