#+ summary:
#+   Where did person X collect and what did he find there?
#+ tags:
#+   - Q-10
#+ endpoint: http://makingsense.liacs.nl/rdf4j-server/repositories/NC
#+ endpoint_in_url: False

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dwciri: <http://rs.tdwg.org/dwc/iri/>
PREFIX dsw: <http://purl.org/dsw/>
PREFIX oa: <http://www.w3.org/ns/oa#>
PREFIX nhc: <http://makingsense.liacs.nl/rdf/nhc/>
PREFIX nc: <http://makingsense.liacs.nl/rdf/nc#>
PREFIX viaf: <http://viaf.org/viaf/>
SELECT DISTINCT ?specieslabel ?locationlabel ?page WHERE {
  ?identification dwciri:toTaxon ?taxon .
  ?taxon rdfs:label ?specieslabel .
  ?taxon nhc:taxonRank nc:species .
  ?organism dsw:hasIdentification ?identification .
  ?organism dsw:hasOccurrence ?occurrence .
  ?occurrence dwciri:recordedBy viaf:45106482 .
  ?occurrence dsw:atEvent ?event .
  ?event dsw:locatedAt ?location .
  ?location rdfs:label ?locationlabel .
  ?anno oa:hasTarget ?roi .
  ?roi oa:hasSource ?page .
  ?anno oa:hasBody ?taxon .
}
